<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerUxqea75\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerUxqea75/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerUxqea75.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerUxqea75\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerUxqea75\appProdProjectContainer(array(
    'container.build_hash' => 'Uxqea75',
    'container.build_id' => 'bda5480a',
    'container.build_time' => 1515413734,
));
