<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerSvued4h\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerSvued4h/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerSvued4h.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerSvued4h\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerSvued4h\appDevDebugProjectContainer(array(
    'container.build_hash' => 'Svued4h',
    'container.build_id' => '9f3d1370',
    'container.build_time' => 1515694243,
));
